### ISSUE TITLE
Update package to add Cbabel-runtime/regenerator

### ISSUE THREAD

**Issue by ericzon** [scoutforpets/node-onesignal#4]
Hey guys, it crashes when I start my api with your lib.

The error message:
Cannot find module 'babel-runtime/regenerator'

It points directly to this line: 
`var OneSignalClient = require('node-onesignal');`

**Comment by pabloruan0710** [comment]
I have this issue too! someone help me please?

**Comment by pabloruan0710** [comment]
@ericzon worked for me 

>  npm install babel-runtime --save

And use 

```var OneSignalClient = require('node-onesignal').default;```

**Comment by ericzon** [comment]
@pabloruan0710  then the solution is move babel-runtime from devDependencies to dependencies.

**Comment by jamesdixon** [comment]
fixed via #5
